---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: armeria
resources:
  - templates/namespace.yaml
  - templates/configmap.yaml
  - templates/statefulset.yaml
secretGenerator:
  - name: armeria-service-account
    files:
      - secrets/GKE_SA_KEY