name: Lint & Build
on:
  push:
    branches:
      - '*'
    tags:
      - '!*'
jobs:
  build_server:
    name: Build Server
    runs-on: ubuntu-latest
    steps:
      - name: Set up go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Run unit tests
        run: go test -race ./...

      - name: Run go vet
        run: go get ./...

      - name: Build server binary
        run: go build -o armeria cmd/armeria/main.go
  build_client:
    name: Build Client
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
        id: node

      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn install
        working-directory: client

      - name: Run linter
        run: yarn lint
        working-directory: client

      - name: Build client
        run: yarn build
        working-directory: client