name: Deploy
on: [release]
jobs:
  deploy:
    name: Deploy Armeria
    runs-on: ubuntu-latest
    steps:
      - name: Clear out client directory
        uses: appleboy/ssh-action@master
        env:
          HOST: armeria.io
          USERNAME: root
          KEY: "${{ secrets.SSH_PRIVATE_KEY }}"
          SCRIPT: rm -rf /opt/armeria/client